FROM golang:1.18.3 as builder
RUN apt-get update && \
    apt-get install -y \
        gcc gcc-mingw-w64 gcc-multilib \
        git make \
        musl-dev liblzma-dev
RUN mkdir -p /go/src/github.com/antmicro/rdfm-artifact
WORKDIR /go/src/github.com/antmicro/rdfm-artifact
ADD ./ .
RUN make build-natives

FROM alpine:3.14.3
RUN apk add xz-dev
COPY --from=builder /go/src/github.com/antmicro/rdfm-artifact/rdfm-artifact* /go/bin/
ENTRYPOINT [ "/go/bin/rdfm-artifact-linux" ]
